#!/bin/bash

echo "### Setup: TXL"

# Ask user if they agree w/ TXL license:
echo "http://txl.ca/ndownload.html"
echo "TXL Version 10.6a"
echo "July 2013"
echo
echo "Copyright 1988-2013 Queen's University at Kingston"
echo
echo "TXL 10.6 and its supporting materials are Copyright 2013 by Queen's University at Kingston (the \"Copyright Holder\") and James R. Cordy (the "Author") under the copyright laws of Canada and international copyright agreements with the United States and other countries signatory to the Berne Convention and/or the Universal Copyright Convention (1971 Paris text)."
echo
echo "TXL 10.6 is provided FREE OF CHARGE for the USE of individuals, companies and institutions PROVIDED that proper ACKNOWLEDGEMENT OF USE of TXL is made in all published work deriving from or depending upon such use."
echo
echo "TXL 10.6 is provided on an AS-IS BASIS, in the hope that it may be useful, but WITHOUT ANY WARRANTY, including WITHOUT ANY IMPLIED WARRANTY AS TO ITS MERCHANTABILITY OR SUITABILITY FOR ANY PARTICULAR PURPOSE."
echo
echo "IN NO EVENT SHALL the Copyright Holder OR the Author BE HELD LIABLE for any direct, indirect, incidental, special, exemplary, or consequential damages (INCLUDING, BUT NOT LIMITED TO, procurement of substitute goods or services; loss of use, data or profits; or business interruption) HOWEVER CAUSED in on any theory of liability, whether in contract, strict liability, or tort (INCLUDING negligence or otherwise) arising IN ANY WAY out of the use of this software, EVEN IF ADVISED of the possibility of such damage."
echo
echo "Permission to copy and redistribute TXL 10.6 is hereby granted PROVIDED that the TXL 10.6 distribution is RETAINED UNMODIFIED IN ITS ENTIRETY including this file, and that NO CHARGE OF ANY KIND is made for such redistribution."
echo
echo "I understand that my download of FreeTXL will be logged, tagged and attributed when I click the \"I Agree\" button above."
echo
echo "(Rev 5.8.13)"
read -p "Do you agree? [y/N]" -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]
then
  curl -sS http://txl.ca/ndownload/25266-txl10.6a.linux64.tar.gz -o /shared/txl.tar.gz

  tar xfz /shared/txl.tar.gz -C "$HOME"
  mv "$HOME/txl10.6a.linux64" "$HOME/txl"
  echo "# txl initialization" >> "$HOME/.bashrc"
  echo 'export PATH="$PATH:$HOME/txl/bin"' >> "$HOME/.bashrc"
fi
